# Custom Language File for Launcher Customizer

[ejs.app]
title = "숭멍의 놀이터2"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/sungmeong"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/NNDkkUDpRA"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/sungmeong"
supportLink = "https://github.com/CustomLauncherLab/sungmeong/issues"

[ejs.welcome]
welcomeHeader = "숭멍의 놀이터2"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."