# Custom Language File for Launcher Customizer

[ejs.app]
title = "숭 멍"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/sungmeong"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/XXCDuJA4aw"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/sungmeong"
supportLink = "https://github.com/CustomLauncherLab/sungmeong/issues"

[ejs.welcome]
welcomeHeader = "숭 멍"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
